#!/bin/bash
alias ls=rm 0-alias 10-love_exponent_breath 11-binary_to_decimal 12-combinations 13-print_float 6-create_local_variable 7-create_global_variable 8-true_knowledge 9-divide_and_rule README.md
